gymManageSys/gymManageSys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] +static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

admin.site.site_header  =  "GMS Addminstration"  
admin.site.site_title  =  "GMS Administration"
admin.site.index_title  =  "GMS Administration"

gymManageSys/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),
    path('faq', views.faq_list, name='faq'),
    path('enquiry', views.enquiry, name='enquiry'),
    path('gallery', views.gallery, name='gallery'),
    path('gallerydetail/<int:id>', views.gallery_detail, name='gallery_detail'),
    path('pricing', views.pricing, name='pricing'),
    path('accounts/signup', views.signup, name='signup'),
    path('checkout/<int:plan_id>', views.checkout, name='checkout'),
    path('checkout_session/<int:plan_id>', views.checkout_session, name='checkout_session'),
    path('pay_success', views.pay_success, name='pay_success'),
    path('pay_cancel', views.pay_cancel, name='pay_cancel'),
    # User Dashboard Section start
    path('user_dashboard', views.user_dashboard, name='user_dashboard'),
    path('update-profile', views.update_profile, name='update_profile'),
    path('attendance',views.attendance,name="attendance"),
    # Trainer login
    path('trainerlogin', views.trainerlogin, name='trainerlogin'),
    path('trainerlogout', views.trainerlogout, name='trainerlogout'),
    path('trainer_dashboard', views.trainer_dashboard, name='trainer_dashboard'),
    path('trainer_profile', views.trainer_profile, name='trainer_profile'),
    path('trainer_subscribers', views.trainer_subscribers, name='trainer_subscribers'),
    path('trainer_payments', views.trainer_payments, name='trainer_payments'),
    path('trainer_changepassword', views.trainer_changepassword, name='trainer_changepassword'),
    path('trainer_notifs', views.trainer_notifs, name='trainer_notifs'),
    # Messages
    path('messages', views.trainer_msgs, name='messages'),
    # Notifications
    path('notifs', views.notifs, name='notifs'),
    path('get_notifs', views.get_notifs, name='get_notifs'),
    path('mark_read_notif', views.mark_read_notif, name='mark_read_notif'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gymManageSys/main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json

# Usuario
#class displayusername(models.Model):
    #user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    #username=models.CharField(max_length=100)
    
# Banners
class Banners(models.Model):
    img=models.ImageField(upload_to="banners/")
    alt_text=models.CharField(max_length=150)
    
    class Meta:
        verbose_name_plural='Banners'

    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
         
    
# Create your models here.
class Service(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()
    img=models.ImageField(upload_to="services/", null=True)
    
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
    
# Pages
class Page(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()
    
    def __str__(self):
        return self.title
    
# FAQ
class Faq(models.Model):
    quest=models.TextField()
    ans=models.TextField()
    
    def __str__(self):
        return self.quest
    
# Enquiry Model
class Enquiry(models.Model):
    full_name=models.CharField(max_length=150)
    email=models.CharField(max_length=150)
    detail=models.TextField()
    send_time=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.quest
    
# Gallery Model
class Gallery(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()
    img=models.ImageField(upload_to="gallery/", null=True)
    
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
            
# Gallery Images
class GalleryImage(models.Model):
    gallery=models.ForeignKey(Gallery,on_delete=models.CASCADE, null=True)
    alt_text=models.CharField(max_length=150)
    img=models.ImageField(upload_to="gallery_imgs/", null=True)
    
    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
    
# Subscription Plans
class SubPlan(models.Model):
    title=models.CharField(max_length=150)
    price=models.IntegerField()
    max_member=models.IntegerField(null=True)
    highlight_status=models.BooleanField(default=False, null=True)
    validity_days=models.IntegerField(null=True)
    
    def __str__(self):
        return self.title
    
 # Subscription Plans Features
class SubPlanFeature(models.Model):
    # subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE)
    subplan= models.ManyToManyField(SubPlan)
    title=models.CharField(max_length=150)   
    
    def __str__(self):
        return self.title
    
# Package Discounts
class PlanDiscount(models.Model):
    subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE)
    total_months=models.IntegerField()
    total_discount= models.IntegerField()
    
    def __str__(self):
        return str(self.total_months)

#Subscriber
class Subscriber(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile=models.CharField(max_length=20)
    address= models.TextField()
    img=models.ImageField(upload_to="subs/", null=True)
    
    def __str__(self):
        return str(self.user)
    
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' % (self.img.url))
        else:
            return 'no-image'
    
@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwrags):
    if created:
        Subscriber.objects.create(user=instance)
        
#Subscription
class Subscription(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan=models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    price=models.CharField(max_length=50)
    reg_date=models.DateField(null=True)
    end_date=models.DateField(null=True)
    
# Trainer
class Trainer(models.Model):
    full_name=models.CharField(max_length=100)
    username= models.CharField(max_length=100, null=True)
    pwd = models.CharField(max_length=50, null=True)
    mobile=models.CharField(max_length=100)
    address=models.TextField()
    is_active=models.BooleanField(default=False)
    detail=models.TextField()
    img=models.ImageField(upload_to="trainers/", null=True)
    salary= models.IntegerField(default=0)
    
    facebook = models.CharField(max_length=200, null=True)
    twitter = models.CharField(max_length=200, null=True)
    pinterest = models.CharField(max_length=200, null=True)
    youtube = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.full_name)
    
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' % (self.img.url))
        else:
            return 'no-image'
        
class Notify(models.Model):
    notify_detail=models.TextField()
    read_by_user=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    read_by_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True,blank=True)
    
    def __str__(self):
        return str(self.notify_detail)
    
# Markas Read Notification By User
class NotifUserStatus(models.Model):
    notif=models.ForeignKey(Notify, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural='Notification Status'
# assing subscriber to Trainer
class AssignSubscriber(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return str(self.user)

#TrainerSalary model
class TrainerSalary(models.Model):
    trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
    amt=models.IntegerField()
    amt_date=models.DateField()
    remarks=models.TextField(blank=True)

    class Meta:
        verbose_name_plural='Trainer Salary'

    def __str__(self):
        return str(self.trainer.full_name)

# Trainer Notificatios
class TrainerNotification(models.Model):
    notif_msg=models.TextField()

    def __str__(self):
        return str(self.notif_msg)
    
    def save(self,*args, **kwargs):
        super(TrainerNotification,self).save(*args, **kwargs)
        channel_layer=get_channel_layer()
        notif=self.notif_msg
        total=TrainerNotification.objects.all().count()
        async_to_sync(channel_layer.group_send)(
            'noti_group_name',{
            'type':'send_notification',
            'value':json.dumps({'notif':notif, 'total':total})
            }
        )

# Markas Read Notification By Trainer
class NotifTrainerStatus(models.Model):
    notif=models.ForeignKey(TrainerNotification, on_delete=models.CASCADE)
    trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural='Trainer Notification Status'

# SubscriberMsg
class TrainerMsg(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)
    message=models.TextField()
   

    class Meta:
        verbose_name_plural='Messages For Trainer'
        
# app settings
class AppSetting(models.Model):
    title=models.CharField(max_length=150) 
    logo_img=models.ImageField(upload_to='app_logos/')
    
    def __str__(self):
        return str(self.title)
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.logo_img.url))

# Registro de asistencia
class Attendance(models.Model):
    Selectdate=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Login=models.CharField(max_length=200, null=True)
    Logout=models.CharField(max_length=200, null=True)
    SelectWorkout=models.CharField(max_length=200, null=True)
    img=models.ForeignKey(Subscriber,on_delete=models.CASCADE, null=True)
    
    def __int__(self):
        return self.id
    
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' % (self.img.img.url))
        else:
            return 'no-image'
    

gymManageSys/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.models import User
from . import models

class EnquiryForm(forms.ModelForm):
    class Meta:
        model=models.Enquiry
        fields=('full_name', 'email','detail')
        
class SignUp(UserCreationForm):
    class Meta:
        model= User
        fields=('first_name','last_name','email','username','password1','password2')
        
class ProfileForm(UserChangeForm):
    class Meta:
        model= User
        fields=('first_name','last_name','email','username')
        
class TrainerLoginForm(forms.ModelForm):
    class Meta:
        model= models.Trainer
        fields=('username','pwd')
        
        widgets = {
           'pwd': forms.PasswordInput(),
        }

class TrainerProfileForm(forms.ModelForm):
    class Meta:
        model= models.Trainer
        fields=('full_name','mobile','address','detail','img')

class TrainerChangePassword(forms.Form):
    new_password=forms.CharField(widget=forms.PasswordInput, required=True)
    


#class AttendanceForm(forms.ModelForm):
    #class Meta:
        #model= models.Attendance
        


        

        



    
        

gymManageSys/main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href= "{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <link href= "{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet" />
    <!-- include jquery -->
	<script type="text/javascript" src="{% static 'jquery-3.7.0.min.js' %}"></script>
    
	<!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="static/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="static/assets/css/style.css" rel="stylesheet">

	<title>{{title}}</title>
  </head>
  <body>
<!-- ======= Header ======= -->
<header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="/">{{title}}<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <a href="index.html" class="logo me-auto me-lg-0">{{logo}}</a>

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'home' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'gallery' %}">Galeria</a></li>
          <li><a class="nav-link scrollto" href="{% url 'pricing' %}">Precios</a></li>
          <li><a class="nav-link scrollto " href="{% url 'enquiry' %}">Solicitud</a></li>
          <li class="dropdown"><a href="#"><span>Mi Cuenta</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
				{% if not request.user.is_authenticated %}
					{% if request.session.trainerLogin %}

					<li><a href="{% url 'trainer_dashboard' %}">Dashboard</a></li>
					<li><a href="{% url 'trainerlogout' %}">Logout</a></li>
			  		{% else %}
					<li><a href="{% url 'trainerlogin' %}">Login de Entrenador</a></li>
					<li><a href="{% url 'signup' %}">Registrarse</a></li>
					<li><a href="{% url 'login' %}">Login</a></li>
					{% endif %}
				{% else %}
				<li><a href="{% url 'user_dashboard' %}">Dashboard</a></li>
				<li><a href="{% url 'update_profile' %}">Perfil</a></li>
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% endif %}
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      {% if  request.user.is_authenticated %}
      <a href="/" class="get-started-btn scrollto">Bienvenido</a>
      {% endif %}
    </div>
  </header><!-- End Header -->

  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-10 col-lg-10">

    {% block content %}

    {% endblock %}

    <!-- Footer Start-->
    <footer class="container py-5">
	    <p class="float-end"><a href="#">Back to top</a></p>
	    <p>© 2017–2021 Arnold GYM, Inc. · 
            <a href="{% url 'pagedetail' 2 %}">Privacy</a> · 
            <a href="{% url 'pagedetail' 3 %}">Terms</a> . 
            <a href="{% url 'faq' %}">FAQ</a>
			<a href="#">Contact Us</a>
        </p>
	  </footer>
	  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="static/assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="static/assets/vendor/aos/aos.js"></script>
  <script src="static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="static/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="static/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="static/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="static/assets/js/main.js"></script>

    <!-- Bootstrap Bundle -->
    <script src= "{% static 'bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

gymManageSys/main/templates/cancel.html
{% extends 'base.html' %}

 {% block content %}
    <!-- Main Start -->
    <main>
        <!-- Services -->
        <section class="container my-4">
            <h3>Lo sentimos, operación cancelada. Intente de nuevo</h3>
        </section>
        <!-- End -->
    </main>
    <!-- End -->
{% endblock %}

gymManageSys/main/templates/checkout.html
{% extends 'base_copy.html' %}
{% load static %}
{% block content %}
<!-- Main Start -->
<main>
    <!-- Services -->
<form method="post" action="">
    {% csrf_token %}
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
            <table class="table table-bordered">
                <thead class="table-warning">
                    <tr>
                        <th>Plan</th>
                        <th>Detalle del Plan</th>
                        <th>Pago por:</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <table class="table-bordered table">
                                <tr>
                                    <th>Subsciptor</th>
                                    <td><select class="form-control mt-2" id="subscriptor" name="subscriptor" required>
                                        <option selected>Seleccione un subscriptor</option>
                                        {% for result in displayusername %}
                                        <option value={{result.id}}>{{result.username}}</option>
                                        {% endfor %}
                                      </select>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Nombre</th>
                                    <td>{{plan.title}}</td>
                                </tr>
                                <tr>
                                    <th>Precio</th>
                                    <td>${{plan.price}}</td>
                                </tr>
                                <tr>
                                    <th>Cantidad Maxima de Cupos</th>
                                    <td>30</td>
                                </tr>
                                <tr>
                                    <th>Ya registrados</th>
                                    <td>15</td>
                                </tr>
                                <tr>
                                    <th>Cupos disponibles</th>
                                    <td>15</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <ul class="list-unstyled">
                                {% for feature in plan.subplanfeature_set.all %}
                                <li>-{{feature.title}}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <table class="table table-bordered">
                                {% for discount in plan.plandiscount_set.all %}
                                <tr>
                                    <td><input data-planprice="{{plan.price}}" 
                                        data-discount="{{discount.total_discount}}" 
                                        type="radio" id="validity{{discount.id}}" name="validity" 
                                        class="select-validity" value=
                                        "{{discount.total_months}}"/></td>
                                    <th><label for="validity{{discount.id}}">{{discount.total_months}}
                                        Month</label></th>
                                    <td>{{discount.total_discount}}%</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </td>
                    </tr>
                </tbody>
                <tfoot class="table-info">
                    <tr>
                        <td></td>
                        <th>Monto Total</th>
                        <td><b>$<span class="totalAmount">150</span></b></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                        <td>
                            
                                
                                <input type="submit" value="Proceed to Payment" class="btn 
                                btn-primary" />
    
                        </td>
                    </tr>
                </tfoot>
            </table>
    </section>
</form>
    <!-- End -->
</main>
<!-- End -->
<script type="text/javascript">
$(document).ready(function(){
    $(".select-validity").on('click',function(){
        var _planPrice=$(this).attr('data-planprice');
        var _planDisc=$(this).attr('data-discount');
        var _planValid=$(this).val();
        var _totalPrice=_planPrice*_planValid;
        if(_planDisc>0){
            var _discountedPrice=_totalPrice*_planDisc/100;
            _discountedPrice=_totalPrice-_discountedPrice;
        }else{
            var _discountedPrice=_totalPrice;
        }
        $(".totalAmount").text(_discountedPrice);
    });
});
</script>
{% endblock %}

gymManageSys/main/templates/faq.html
{% extends 'base.html' %}

 {% block content %}
    <!-- Main Start -->
    <main>
        <!-- Services -->
        <section class="container my-4">
            <h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
            <div class="accordion" id="accordionExample">
                {% for faq in faqs %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                    {{faq.quest}}
                </button>
                </h2>
                <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    {{faq.ans}}
                </div>
            </div>
            </div>
            {% endfor %}
            </div>
        </section>
        <!-- End -->
    </main>
    <!-- End -->
{% endblock %}

gymManageSys/main/templates/gallery.html
{% extends 'base.html' %}

 {% block content %}
<!-- Main Start -->
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Galeria</h1>
        <div class="row">
            {% for gallery in gallerys %}
            <div class="col-md-4 mb-4">
                <div class="card">
                  <img src="{{gallery.img.url}}" class="card-img-top" alt="{{gallery.title}}">
                  <div class="card-body">
                    <h5 class="card-title">{{gallery.title}}</h5>
                    <p class="card-text">{{gallery.detail}}</p>
                    <a href="{% url 'gallery_detail' gallery.id %}" class="btn btn-primary">View All</a>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- End -->
</main>
<!-- End -->
{% endblock %}

gymManageSys/main/templates/gallery_imgs.html
{% extends 'base_copy.html' %}

 {% block content %}
<!-- Main Start -->
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gallery.title}} Imagenes</h1>
        <div class="row">
            {% for gimg in gallery_imgs %}
            <div class="col-md-4 mb-4">
                <div class="card">
                  <img src="{{gimg.img.url}}" class="card-img-top" alt="{{gimg.alt_text}}">
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- End -->
</main>
<!-- End -->
{% endblock %}

gymManageSys/main/templates/orderemail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Confirmación de Orden</title>
    </head>
    <body>
        <h3>{{title}}</h3>
    </body>
</html>

gymManageSys/main/templates/page.html
{% extends 'base.html' %}
{% block content %}
 <!-- Main Start -->
 <main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">{{page.title}}</h1>
        <p>{{page.detail}}</p>
    </section>
    <!-- End -->
  </main>
  <!-- End -->
{% endblock %}

gymManageSys/main/templates/pricing.html
{% extends 'base_copy.html' %}
{% load static %}
{% load check_package %}
{% load mathfilters %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}"
<!-- Main Start -->
<section class="container my-4">
  <h1 class="text-center mb-4 section-heading border-bottom pb-2">Programas</h1>
<main>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
        {% if plan.highlight_status %}
        <div class="card-header py-3 text-white bg-primary border-primary">
        {% else %}
        <div class="card-header py-3">
        {% endif %}
        <h4 class="my-0 fw-normal">{{plan.title}}</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title text-muted fw-light">${{plan.price}}<small class="text-muted fw-light">/{{plan.validity_days}} Días</small>
        </h1>
        <p class="text-success">Máximo Subscriptores por seccion {{plan.max_member|sub:plan.total_members}}</p>
        <ul class="list-unstyled mt-3 mb-4">
            {% for feature in plan.subplanfeature_set.all %}
          <li>-{{feature.title}}</li>
          {% endfor %}
        </ul>
        
        {% if request.user.is_authenticated %}
        {% if request.user.is_staff %}
          {% check_user_package request.user.id plan.id as check_pckg %}
          {% check_pckg_validity request.user.id plan.id as check_validity %}
            {% if check_pckg %}
              {% if check_validity %}
                <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Comprar</a>
              {% else %}
                <a href="#" class="w-100 btn btn-lg btn-dark disabled">Comprado</a>
              {% endif %}
            {% else %}
              <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Comprar</a>
            {% endif %}
        {% else %}
        <a href="#" class="w-100 btn btn-lg btn-dark disabled">Contactar al personal</a>
        {% endif %}
        {% else %}
        <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Comprar</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<h2 class="display-6 text-center mb-4">Comparativo de planes</h2>

<div class="table-responsive">
  <table class="table text-center">
    <thead>
      <tr>
        <th style="width: 34%;"></th>
        {% for plan in plans %}
        <th style="width: 22%;">{{plan.title}}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
        {% for feature in dfeatures %}
      <tr>
        <th scope="row" class="text-start">{{feature.title}}</th>
        {% for plan in plans %}
        <td>
            {% if plan in feature.subplan.all %}
            <i class="bi bi-check-lg"></i>
            {% else %}
            <i class="bi bi-x text-danger"></i>
            {% endif %}
        </td>
        {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</main>
</section>
<!-- End -->
{% endblock %}

gymManageSys/main/templates/success.html
{% extends 'base.html' %}

 {% block content %}
    <!-- Main Start -->
    <main>
        <!-- Services -->
        <section class="container my-4">
            <h3>Gracias por su pago</h3>
        </section>
        <!-- End -->
    </main>
    <!-- End -->
{% endblock %}